import { api } from "@/lib/api";
import { FeedbackForm } from "./FeedbackForm";

export const dynamic = "force-dynamic";

interface PageProps {
  searchParams?: { constituency_id?: string };
}

export default async function FeedbackPage({ searchParams }: PageProps) {
  const constituencyId = searchParams?.constituency_id ? Number(searchParams.constituency_id) : undefined;

  const [clusters, constituencies] = await Promise.all([
    constituencyId
      ? api.feedbackClusters({ constituency_id: constituencyId })
      : api.feedbackClusters(),
    api.constituencies(),
  ]);

  const sentimentTone = (s: number): string => {
    if (s > 0.3) return "text-green";
    if (s < -0.3) return "text-saffron";
    return "text-ink-muted";
  };

  return (
    <div>
      <header className="ruled pt-3 mb-10">
        <p className="ident">Citizen Voice</p>
        <h1 className="font-display font-semibold text-5xl md:text-6xl mt-2 tracking-tightish">
          What citizens are saying.
        </h1>
        <p className="mt-4 text-ink-soft max-w-column leading-relaxed">
          Submitted feedback is grouped by issue and constituency. Aggregations are
          generated by the same nonpartisan pipeline that handles government documents —
          summaries reflect what people wrote, nothing more.
        </p>
      </header>

      <div className="grid md:grid-cols-3 gap-x-12 gap-y-12">
        <section className="md:col-span-2">
          <h2 className="font-display text-2xl font-semibold mb-6 border-b border-paper-line pb-3">
            Recurring feedback
          </h2>
          {clusters.length === 0 ? (
            <p className="text-ink-muted py-12">
              No feedback clusters yet. The clustering job runs nightly — submit feedback
              below to seed the first cluster.
            </p>
          ) : (
            <ul className="divide-y divide-paper-line">
              {clusters.map((c) => (
                <li key={c.id} className="py-5">
                  <div className="flex items-center gap-3 flex-wrap">
                    <span className="font-mono text-xs text-ink-muted">{c.count} submissions</span>
                    <span className="text-paper-line">·</span>
                    <span className={`text-xs uppercase tracking-wideish ${sentimentTone(c.avg_sentiment)}`}>
                      {c.avg_sentiment > 0.3 ? "Positive lean" : c.avg_sentiment < -0.3 ? "Negative lean" : "Mixed"}
                    </span>
                  </div>
                  <p className="mt-2 text-ink-soft leading-relaxed max-w-column">{c.summary}</p>
                </li>
              ))}
            </ul>
          )}
        </section>

        <aside className="md:col-span-1 md:border-l md:border-paper-line md:pl-8">
          <p className="label-caps mb-3">Submit your feedback</p>
          <p className="text-sm text-ink-soft leading-relaxed mb-5">
            Submissions are moderated. We do not store your IP address — only a salted hash
            for rate-limiting.
          </p>
          <FeedbackForm
            constituencies={constituencies}
            preselectedConstituencyId={constituencyId}
          />
        </aside>
      </div>
    </div>
  );
}
