"""Citizen feedback (raw submissions) and clusters (aggregated views)."""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import JSON, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base

if TYPE_CHECKING:
    from app.models.document import Document
    from app.models.geography import Constituency
    from app.models.topic import Topic


class CitizenFeedback(Base):
    __tablename__ = "citizen_feedback"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    constituency_id: Mapped[int | None] = mapped_column(
        ForeignKey("constituencies.id"), nullable=True, index=True
    )
    document_id: Mapped[int | None] = mapped_column(ForeignKey("documents.id"), nullable=True)
    topic_id: Mapped[int | None] = mapped_column(ForeignKey("topics.id"), nullable=True, index=True)

    text: Mapped[str] = mapped_column(Text, nullable=False)
    language: Mapped[str] = mapped_column(String(8), nullable=False, default="en")

    # -1.0 (very negative) .. +1.0 (very positive); 0 if unknown
    sentiment: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    submitted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=datetime.utcnow
    )

    # Hashed IP for rate-limiting & abuse mitigation. Never store raw IP.
    ip_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # pending | approved | rejected
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="pending")

    constituency: Mapped["Constituency | None"] = relationship()
    document: Mapped["Document | None"] = relationship()
    topic: Mapped["Topic | None"] = relationship()


class FeedbackCluster(Base):
    """Aggregated view, regenerated by the clustering job."""
    __tablename__ = "feedback_clusters"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    topic_id: Mapped[int | None] = mapped_column(ForeignKey("topics.id"), nullable=True, index=True)
    constituency_id: Mapped[int | None] = mapped_column(
        ForeignKey("constituencies.id"), nullable=True, index=True
    )
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    avg_sentiment: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    last_updated: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=datetime.utcnow
    )
    sample_feedback_ids_json: Mapped[list[int] | None] = mapped_column(JSON, nullable=True)

    topic: Mapped["Topic | None"] = relationship()
    constituency: Mapped["Constituency | None"] = relationship()
